site_name: Atlas Linux
docs_dir: pages

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      linenums: true            # show line numbers
      anchor_linenums: true     # line numbers are clickable
      pygments_lang_class: true # needed for correct CSS classes
  - pymdownx.superfences         # lets you use triple backticks with language specifiers
